language: go
sudo: false
go_import_path: go.uber.org/config

env:
  global:
    - GO111MODULE=on

matrix:
  include:
  - go: 1.12.x
  - go: 1.13.x

before_install:
  - go version

# Download modules to the cache.
install:
  - go mod download

script:
  - make test

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
